### ISSUE TITLE
Cannot decode HTML entity

### ISSUE THREAD

**Issue by meichengg** [khalyomede/html#1]
Hi, i'm having problem when decoding this HTML entity with your library.

```v
module main

import khalyomede.html

fn main() {
	a := 'l&ograve;ng'
	println(html.decode(a))
}
```

The error i get is:

```text
/.vmodules/khalyomede/html/entity_to_text.v:9:9: error: cannot cast `!i64` to `byte` (alias to `u8`)
    7 | */
    8 | fn entity_to_text(text string) string {
    9 |     return byte(strconv.parse_int(text.replace("&#x", "").replace(";", ""), 16, 8)).ascii_str()
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   10 | }
```

**Comment by khalyomede** [comment]
Hi, sorry for the long wait. I'm not working with V Lang these days. Could you let me know if this is an urgent issue or not. If yes, I might give some time to check it. If it is not urgent I will postpone finding a fix for a later time.

**Comment by meichengg** [comment]
Hey, thanks for getting back. I'm no longer working with V, it's quite complicated and time-consuming for my works. Anyway, thanks for your effort. Take care, have a nice day!
